# Generated by Django 5.0.1 on 2025-12-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sessions_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_remaining', models.IntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_packages', to='clients.client')),
                ('session_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_packages', to='packages.sessionpackage')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionpackage',
            index=models.Index(fields=['trainer', 'is_active'], name='packages_se_trainer_c2c9a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionpackage',
            unique_together={('trainer', 'name')},
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['client', 'expiry_date'], name='packages_cl_client__568efa_idx'),
        ),
    ]
