# Generated by Django 5.0.1 on 2025-12-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('trainers', '0003_paymentlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(help_text='Default duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainer', 'is_active'], name='packages_se_trainer_4c0597_idx')],
                'unique_together': {('trainer', 'name')},
            },
        ),
    ]
