# Generated by Django 5.0.1 on 2025-12-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_branding', models.BooleanField(default=False, help_text="Remove 'Powered by TrainerHub' footer")),
                ('custom_logo', models.ImageField(blank=True, help_text='Custom logo (max 500KB, PNG/SVG)', null=True, upload_to='whitelabel/logos/')),
                ('custom_favicon', models.ImageField(blank=True, help_text='Custom favicon (16x16 or 32x32)', null=True, upload_to='whitelabel/favicons/')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#10b981', help_text='Secondary brand color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent color (hex)', max_length=7)),
                ('text_color', models.CharField(default='#1f2937', help_text='Primary text color (hex)', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color (hex)', max_length=7)),
                ('font_family', models.CharField(default='Inter', help_text='Google Fonts font family name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel_settings', to='trainers.trainer')),
            ],
            options={
                'verbose_name': 'White Label Settings',
                'verbose_name_plural': 'White Label Settings',
            },
        ),
    ]
