# Generated by Django 5.0.1 on 2025-12-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_whitelabelsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_link', models.URLField(blank=True, help_text='Stripe payment link')),
                ('paypal_link', models.URLField(blank=True, help_text='PayPal.me or payment link')),
                ('venmo_username', models.CharField(blank=True, help_text='Venmo username (without @)', max_length=100)),
                ('zelle_email', models.EmailField(blank=True, help_text='Zelle email or phone', max_length=254)),
                ('cashapp_username', models.CharField(blank=True, help_text='Cash App $cashtag (without $)', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number_last4', models.CharField(blank=True, help_text='Last 4 digits only', max_length=4)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('custom_links', models.JSONField(default=list, help_text="List of custom payment links: [{'label': 'Link Name', 'url': 'https://...'}]")),
                ('show_on_public_pages', models.BooleanField(default=True)),
                ('payment_instructions', models.TextField(blank=True, help_text='Custom instructions for clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='trainers.trainer')),
            ],
            options={
                'verbose_name': 'Payment Links',
                'verbose_name_plural': 'Payment Links',
            },
        ),
    ]
