# Generated by Django 5.0.1 on 2025-12-30 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_customdomain_domainverificationlog_and_more'),
        ('trainers', '0002_whitelabelsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('category', models.CharField(max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
                ('template_data', models.JSONField(default=dict)),
                ('available_for_plans', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='pages_paget_categor_82d637_idx'), models.Index(fields=['is_premium'], name='pages_paget_is_prem_b4f8b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.customdomain')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='trainers.trainer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.pagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('services', 'Services'), ('about', 'About'), ('testimonials', 'Testimonials'), ('contact', 'Contact'), ('pricing', 'Pricing'), ('gallery', 'Gallery'), ('faq', 'FAQ'), ('booking', 'Booking')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['page', 'order'], name='pages_pages_page_id_af72a7_idx'), models.Index(fields=['section_type'], name='pages_pages_section_aa46bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['trainer', 'is_published'], name='pages_page_trainer_5da2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['trainer', 'slug'], name='pages_page_trainer_c04c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published', 'published_at'], name='pages_page_is_publ_f0e48d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('trainer', 'slug')},
        ),
    ]
