# Generated by Django 5.0.1 on 2025-12-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_last_payment_date_client_payment_status_and_more'),
        ('trainers', '0003_paymentlinks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['trainer', 'is_active'], name='clients_cli_trainer_1df325_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['trainer', 'payment_status'], name='clients_cli_trainer_c52b21_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['trainer', 'created_at'], name='clients_cli_trainer_42f3d1_idx'),
        ),
    ]
