# Generated by Django 5.0.1 on 2025-12-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0003_client_clients_cli_trainer_1df325_idx_and_more'),
        ('packages', '0002_service'),
        ('trainers', '0003_paymentlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.service'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trainer', 'status'], name='bookings_bo_trainer_319cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trainer', 'status', 'start_time'], name='bookings_bo_trainer_f7dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'start_time'], name='bookings_bo_service_137774_idx'),
        ),
    ]
