# Generated by Django 5.0.1 on 2025-12-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verifying', 'Verifying DNS'), ('verified', 'DNS Verified'), ('provisioning_ssl', 'Provisioning SSL'), ('active', 'Active'), ('failed', 'Verification Failed'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_token', models.CharField(max_length=100, unique=True)),
                ('verification_method', models.CharField(choices=[('cname', 'CNAME Record'), ('txt', 'TXT Record')], default='cname', max_length=20)),
                ('dns_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('ssl_provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_provider', models.CharField(default='letsencrypt', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_domains', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('dns', 'DNS Check'), ('ssl', 'SSL Provisioning')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='admin_panel.customdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['domain'], name='admin_panel_domain_2dce2a_idx'),
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['status'], name='admin_panel_status_32e469_idx'),
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['trainer', 'status'], name='admin_panel_trainer_d73ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='domainverificationlog',
            index=models.Index(fields=['domain', '-created_at'], name='admin_panel_domain__273717_idx'),
        ),
    ]
