# Generated by Django 5.0.1 on 2025-12-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bookings_count', models.IntegerField(default=0)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_clients', models.IntegerField(default=0)),
                ('active_clients', models.IntegerField(default=0)),
                ('average_session_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trainer', 'date'], name='analytics_d_trainer_ba8b8b_idx')],
                'unique_together': {('trainer', 'date')},
            },
        ),
    ]
